# Replace '<PUT INFO HERE>' with the credentials from here: 
# https://console.cloud.google.com/apis/credentials?project=
client_config_backend: file
client_config:
  client_id: <PUT INFO HERE>
  client_secret: <PUT INFO HERE>

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive